### ISSUE TITLE
MVP -- Repos List

### ISSUE THREAD

**Issue by GraceRenewed** [nss-evening-cohort-28/gitsub-team-2#13]
#User Story
As a user interested in code, I would want a list of my repos to access easily. From the repos page I would want a direct link to access the repos, I would want the ability to organize my list in a preferred order and have access to the most recent repos I have to work on. I would also like a way to do a search of all my repos. As a user I would want to be able to use tags on my repos so others can easily find them within gitHub.

#Acceptance Criteria
Create a repos section which would contain the users repos. In each repo listing have a title and description of the repo with tags. On each repo on the repo have an option to favorite it, language types, fork button and date of last update.

#Dependencies
#10 
Will interact with pinned repos element. 

#Dev Notes

![Image](https://github.com/user-attachments/assets/8d46ea87-c088-49fb-846d-63caaaaf4301)

**Comment by Gnashed** [comment]
Almost finished. Working on adding a star for favoriting.

**Comment by Gnashed** [comment]
Added a star icon thanks to Bootstrap icons - [](https://icons.getbootstrap.com/icons/star/)

I'm still working on adding an event listener that will change the star to a solid color on click.
